### ISSUE TITLE
Add support for Python 3.7

### ISSUE THREAD

**Issue by mmtrebuchet** [kundajelab/genomelake#21]
genomelake lists itself as compatible with python 3.6, and this makes it the only package in basepair's conda environment that prevents me from using python 3.7 and its coroutine goodness. Unless genomelake is somehow incompatible with python 3.7, it should be a simple matter of changing setup.py, I believe.

**Comment by Avsecz** [comment]
What error message are you getting on python 3.7?

**Comment by mmtrebuchet** [comment]
If I set the python version in conda-env-cpu.yml to python=3.7, then the solve fails to generate an environment, with a spew of version requirements. If I comment out genomelake, then the build succeeds. If I move genomelake to the pip: section, then I get a bunch of compiler errors about structs and such at the C level.

**Comment by Avsecz** [comment]
I see. You could install cython, pybigwig, pysam, bcolz and bedtools from conda and then genomelake from pip:

```yaml
name: env
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- python=3.7
- pybedtools>=0.7.10
- bedtools>=2.27.1
- pybigwig>=0.3.10
- bcolz>=1.1
- pysam>=0.14.0
- cython
- pip
- pip:
  - genomelake
```

Also, you have to make sure that your machine has the build tools installed. Run `sudo apt-get install build-essential` if you are using ubuntu.
